#!/usr/bin/env bash
#
# vps-bootstrap.sh — One-shot, self-contained production bringup for Izzi Auto Post.
#
# Designed to be run on a fresh Ubuntu VPS as root (e.g. pasted into the Vultr web
# Console where SSH password login is disabled). It is idempotent: re-running it
# re-uses what already exists and only fills gaps.
#
#   bash <(curl -fsSL https://raw.githubusercontent.com/kentzu213/auto-post-tool/master/scripts/vps-bootstrap.sh)
#
# What it does, in order:
#   1. Install Docker Engine + Compose plugin + git if missing.
#   2. Clone (or update) the repo into /opt/autopost.
#   3. Derive sslip.io hostnames from the machine's public IP so Caddy can obtain
#      REAL Let's Encrypt certs without the operator owning a domain:
#        web -> https://app-<ip-dashed>.sslip.io
#        api -> https://api-<ip-dashed>.sslip.io
#   4. Generate a production .env with strong random secrets (openssl) — only on
#      first run; preserved on subsequent runs.
#   5. Write a Caddyfile bound to those hostnames.
#   6. docker compose build + up (postgres/redis/minio/api/worker/web/caddy/backup).
#   7. Run `prisma migrate deploy` (one-shot migrate service) — applies all
#      migrations including the additive AuditLog change.
#   8. Smoke check /health/ready and /version, then print the public URLs.
#
# Safe-by-default: secrets live only in /opt/autopost/.env (chmod 600), never echoed.

set -euo pipefail

REPO_URL="https://github.com/kentzu213/auto-post-tool.git"
DEPLOY_DIR="/opt/autopost"
BRANCH="master"

log()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m[warn] %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31m[ERROR] %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root (paste into the Vultr Console as root)."

# ---------------------------------------------------------------------------
# 1. Base packages: git, curl, openssl, Docker Engine + compose plugin
# ---------------------------------------------------------------------------
log "Ensuring base packages (git, curl, openssl)…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y >/dev/null 2>&1 || true
apt-get install -y git curl openssl ca-certificates >/dev/null 2>&1 || true

if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker Engine…"
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version >/dev/null 2>&1; then
  log "Installing docker compose plugin…"
  apt-get install -y docker-compose-plugin >/dev/null 2>&1 || true
fi
systemctl enable --now docker >/dev/null 2>&1 || true
docker --version
docker compose version

# ---------------------------------------------------------------------------
# 2. Clone / update the repo
# ---------------------------------------------------------------------------
if [ -d "$DEPLOY_DIR/.git" ]; then
  log "Updating existing checkout at $DEPLOY_DIR…"
  git -C "$DEPLOY_DIR" fetch --all --prune
  git -C "$DEPLOY_DIR" checkout "$BRANCH"
  git -C "$DEPLOY_DIR" reset --hard "origin/$BRANCH"
else
  log "Cloning $REPO_URL into $DEPLOY_DIR…"
  git clone --branch "$BRANCH" "$REPO_URL" "$DEPLOY_DIR"
fi
cd "$DEPLOY_DIR"

# ---------------------------------------------------------------------------
# 3. Resolve public IP → sslip.io hostnames (real LE certs, no domain needed)
# ---------------------------------------------------------------------------
log "Resolving public IP…"
PUBLIC_IP="$(curl -fsSL https://api.ipify.org || curl -fsSL https://ifconfig.me || true)"
[ -n "$PUBLIC_IP" ] || die "Could not determine public IP."
IP_DASHED="${PUBLIC_IP//./-}"
APP_HOST="app-${IP_DASHED}.sslip.io"
API_HOST="api-${IP_DASHED}.sslip.io"
log "Public IP: $PUBLIC_IP"
log "Web: https://${APP_HOST}"
log "API: https://${API_HOST}"

# ---------------------------------------------------------------------------
# 4. Generate production .env (first run only; preserved afterwards)
# ---------------------------------------------------------------------------
ENV_FILE="$DEPLOY_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  log ".env already exists — preserving existing secrets."
else
  log "Generating .env with strong random secrets…"
  PG_PW="$(openssl rand -hex 24)"
  MINIO_PW="$(openssl rand -hex 24)"
  JWT_SECRET="$(openssl rand -hex 48)"
  JWT_REFRESH="$(openssl rand -hex 48)"
  ENC_KEY="$(openssl rand -hex 32)"   # 64 hex chars = AES-256 key
  BULL_PW="$(openssl rand -hex 16)"

  cat > "$ENV_FILE" <<EOF
# Generated by vps-bootstrap.sh on $(date -u +%FT%TZ). Secrets — keep chmod 600.
NODE_ENV=production
PORT=3001

# Postgres
POSTGRES_USER=autopost
POSTGRES_PASSWORD=${PG_PW}
POSTGRES_DB=autopost
DATABASE_URL=postgresql://autopost:${PG_PW}@postgres:5432/autopost?schema=public

# Redis
REDIS_HOST=redis
REDIS_PORT=6379

# Object storage (MinIO, internal)
S3_ENDPOINT=http://minio:9000
S3_ACCESS_KEY=autopost
S3_SECRET_KEY=${MINIO_PW}
S3_BUCKET_NAME=autopost-media
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=true
MINIO_ROOT_USER=autopost
MINIO_ROOT_PASSWORD=${MINIO_PW}

# Security
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH}
ENCRYPTION_KEY=${ENC_KEY}
OAUTH_STATE_SECRET=${JWT_SECRET}

# Public URLs / CORS (sslip.io — real Let's Encrypt certs, no domain purchase)
APP_HOST=${APP_HOST}
API_HOST=${API_HOST}
NEXT_PUBLIC_API_URL=https://${API_HOST}
CORS_ORIGINS=https://${APP_HOST}
ACME_EMAIL=admin@${APP_HOST}

# Admin dashboard (Bull Board) basic auth
BULL_BOARD_USER=admin
BULL_BOARD_PASSWORD=${BULL_PW}

# OAuth client secrets — placeholders; real values entered via Settings UI later.
FACEBOOK_CLIENT_ID=
FACEBOOK_CLIENT_SECRET=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
TIKTOK_CLIENT_KEY=
TIKTOK_CLIENT_SECRET=
EOF
  chmod 600 "$ENV_FILE"
  log ".env created (chmod 600). Bull Board password: ${BULL_PW}"
fi

# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a

# ---------------------------------------------------------------------------
# 5. Caddyfile bound to the sslip.io hosts (real ACME TLS)
# ---------------------------------------------------------------------------
log "Writing Caddyfile for ${APP_HOST} / ${API_HOST}…"
cat > "$DEPLOY_DIR/Caddyfile" <<EOF
{
	email ${ACME_EMAIL}
}

${APP_HOST} {
	encode gzip zstd
	reverse_proxy web:3000 {
		header_up X-Forwarded-Proto {scheme}
		header_up X-Forwarded-Host {host}
	}
}

${API_HOST} {
	encode gzip zstd
	reverse_proxy api:3001 {
		header_up X-Forwarded-Proto {scheme}
		header_up X-Forwarded-Host {host}
	}
}
EOF

# ---------------------------------------------------------------------------
# 6. Build + start the stack
# ---------------------------------------------------------------------------
COMPOSE="docker compose -f docker-compose.prod.yml"
log "Building images (this can take several minutes on first run)…"
$COMPOSE build

log "Starting data services (postgres/redis/minio)…"
$COMPOSE up -d postgres redis minio

log "Waiting for postgres to be healthy…"
for i in $(seq 1 30); do
  if $COMPOSE exec -T postgres pg_isready -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

# ---------------------------------------------------------------------------
# 7. Run migrations (one-shot), then bring up app + proxy
# ---------------------------------------------------------------------------
log "Applying database migrations (prisma migrate deploy)…"
$COMPOSE run --rm migrate || warn "migrate returned non-zero (check logs)"

log "Starting api / worker / web / caddy / backup…"
$COMPOSE up -d

# ---------------------------------------------------------------------------
# 8. Smoke check
# ---------------------------------------------------------------------------
log "Smoke check (waiting for API readiness)…"
READY=""
for i in $(seq 1 30); do
  code="$($COMPOSE exec -T api curl -fsS -o /dev/null -w '%{http_code}' http://localhost:3001/health/ready 2>/dev/null || echo 000)"
  if [ "$code" = "200" ]; then READY=1; break; fi
  sleep 3
done

echo
echo "=================================================================="
if [ -n "$READY" ]; then
  echo " ✅ Izzi Auto Post is UP."
else
  echo " ⚠️  API not ready yet — TLS/containers may still be warming up."
  echo "    Check: $COMPOSE ps ; $COMPOSE logs --tail=50 api caddy"
fi
echo "    Web : https://${APP_HOST}"
echo "    API : https://${API_HOST}/health/ready"
echo "    Ver : https://${API_HOST}/version"
echo "    (TLS cert issuance via Let's Encrypt can take ~30-60s on first hit.)"
echo "=================================================================="
$COMPOSE ps
